### ISSUE TITLE
Mopidy deps error in 0.5.2

### ISSUE THREAD

**Issue by vrs01** [woutervanwijk/Pi-MusicBox#200]
Hi! 

When I run `mopidy deps` or `mopidy config`  I get:
```
root@MusicBox:~# mopidy deps
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.19.4', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 64, in main
    create_file_structures_and_config(args, installed_extensions)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 149, in create_file_structures_and_config
    default = config_lib.format_initial(extensions)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/config/__init__.py", line 101, in format_initial
    return description + '\n\n' + _format(config, {}, schemas, False, True)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4560: ordinal not in range(128)

```
What's causing that?

**Comment by kingosticks** [comment]
This looks like https://discuss.mopidy.com/t/mopidy-on-debian-pogolug-startup-fails-with-unicodedecodeerror-solved/428 which is fixed in Mopidy 0.19.5
