### ISSUE TITLE
Clean Install. Web Interface Connection Refused. Restarting Mopidy from SSH shows Python error

### ISSUE THREAD

**Issue by adamnock** [woutervanwijk/Pi-MusicBox#528]
Steps taken

Formatted clean 16GB Sandisk SD
Wrote 0.7RC7 using Etcher
Booted Pi. Waited till grow reboot
Web Interface not accessible (can confirm IP via DHCP given)
SSH'd in. 
Only message in Mopidy log was
2019-06-03 12:32:32,837 - WARNING  /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning

Rebooted. Same issue
Restarted Mopidy from CLI (service mopidy restart)
Still no go but new error in Log

2019-06-03 12:33:03,308 - ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 303, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/commands.py", line 386, in start_backends
    backend.ping().get()
  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 50, in get
    self._data = self._queue.get(True, timeout)
  File "/usr/lib/python2.7/Queue.py", line 168, in get
    self.not_empty.wait()
  File "/usr/lib/python2.7/threading.py", line 244, in wait
    waiter.acquire()
TypeError: 'int' object is not callable

**Comment by adamnock** [comment]
Hmm ok. Literally a minute after opening this issue the browser window I had open with Connection Refused refreshed and loaded the Web UI.

Nothing extra in Log.

Is there a distinct lag between first run and initialization?

**Comment by adamnock** [comment]
Im going to close this. Im sort of convinced its being caused by low power issues due to my USB soundcard. Unplugged it and it seems to be behaving better.
